### ISSUE TITLE
"Password authentication failed for user" error after the upgrade to 2.6.0

### ISSUE THREAD

**Issue by petrlyapin** [strongloop/loopback-connector-postgresql#145]
After the upgrade to 2.6.0 I can not run my loopback project with loopback-connector-postgresql anymore.

Here is the error I get:

`Connection fails:  { error: password authentication failed for user "Lyapin"
    at Connection.parseE (\node_modules\pg\lib\connection.js:543:11)
    at Connection.parseMessage (\node_modules\pg\lib\connection.js:370:17)
    at Socket.<anonymous> (\node_modules\pg\lib\connection.js:109:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
  name: 'error',
  length: 95,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '285',
  routine: 'auth_failed' }`

I use Windows and it looks like with the new version of the connector (which has pg library updated from 4.2.0 to 6.0.0 as well) it tries to use my current user's windows credentials to connect to postgresql instead of the credentials specified in the datasources.json file.

If i use 2.5.0 it works as expected.

**Comment by raymondfeng** [comment]
How does your ds config look like?

**Comment by petrlyapin** [comment]
`{
  "pg": {
    "host": "localhost",
    "port": 5432,
    "url": "postgres://user:password@localhost/database",
    "database": "database",
    "password": "password",
    "name": "pg",
    "user": "user",
    "connector": "postgresql"
  }
}`

**Comment by raymondfeng** [comment]
Can you try the following within your app?
```
 c:> node
> var P = require('pg/lib/connection-parameters')
> var c = new P("postgres://user:password@localhost/database")
undefined
> c
```

What is your printout?

**Comment by raymondfeng** [comment]
You can also use `SET DEBUG=loopback:connector:postgresql` and run your app to see what settings are used.

**Comment by petrlyapin** [comment]
Here is what I get:

```javascript
{
"user":"user",
"database":"database",
"port":5432,
"host":"localhost",
"password":"password",
"binary":false,
"ssl":false,
"client_encoding":"",
"isDomainSocket":false
}
```

**Comment by petrlyapin** [comment]
Here is what I get:

```javascript
{
"user":"user",
"database":"database",
"port":5432,
"host":"localhost",
"password":"password",
"binary":false,
"ssl":false,
"client_encoding":"",
"isDomainSocket":false
}
```

I tried both 2.5.0 and 2.6.0 and I get exactly the same result.

**Comment by petrlyapin** [comment]
I have also tried with the SET DEBUG=loopback:connector:postgresql - results are the same for both versions of the connector:

```javascript
{"host":"localhost","port":5432,"url":"postgres://user:password@localhost/database","database":"database","password":"password","name":"pg","user":"postgres","connector":"postgresql","debug":true}
```

**Comment by raymondfeng** [comment]
Should be fixed now by 2.6.1

**Comment by petrlyapin** [comment]
Nope, I have 2.6.1 now and it is still not working.

**Comment by raymondfeng** [comment]
Hmm, I verified it on both Windows and Mac. One of my tests fails before the fix and works now. It's due to the usage of `url`.

**Comment by ssh24** [comment]
This is not an issue anymore. You can specify the **password** as a part of the `url` or as a config and authentication works.

Here is a sample reproduction:

**datasources.json**
```json
{
  "postgresqlDs": {
    "host": "localhost",
    "port": 5432,
    "url": "",
    "database": "testdb",
    "password": "<pass>",
    "name": "postgresqlDs",
    "user": "<user>",
    "connector": "postgresql"
  },
  "newDs": {
    "host": "",
    "port": 5432,
    "url": "postgres://<user>:<pass>@localhost/testdb",
    "database": "",
    "password": "",
    "name": "newDs",
    "user": "",
    "connector": "postgresql"
  }
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var db2 = app.datasources.newDs;

    db.ping(function(err) {
        if (err) throw err;
        console.log('\nPinged first db.');

        db2.ping(function(err) {
            if (err) throw err;
            console.log('\nPinged second db.');
        });
    });
};
```

**output**
```bash
sakibs-mac:postgresql-145 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Pinged first db.

Pinged second db.
```

**Comment by johnhaire89** [comment]
I installed nodejs and loopback 4 on Windows 10 today and experienced this issue.
Including the username and password in the URL did not fix the issue.
After running "npm update pg" it's using the correct username.


**>npm ls loopback-connector-postgresql**
```
cmc-loopback-api@1.0.0 C:\dev/first-loopback-api
`-- loopback-connector-postgresql@3.8.0
```


**>lb4 --version**
```
@loopback/cli version: 1.26.0

@loopback/* dependencies:
  - @loopback/authentication: ^3.2.3
  - @loopback/boot: ^1.5.12
  - @loopback/build: ^2.1.0
  - @loopback/context: ^1.24.0
  - @loopback/core: ^1.11.0
  - @loopback/metadata: ^1.3.8
  - @loopback/openapi-spec-builder: ^1.2.19
  - @loopback/openapi-v3: ^1.10.2
  - @loopback/repository-json-schema: ^1.11.2
  - @loopback/repository: ^1.15.5
  - @loopback/rest: ^1.24.0
  - @loopback/testlab: ^1.9.5
  - @loopback/docs: ^2.6.0
  - @loopback/example-hello-world: ^1.2.20
  - @loopback/example-log-extension: ^1.2.20
  - @loopback/example-rpc-server: ^1.2.20
  - @loopback/example-todo: ^1.9.1
  - @loopback/example-soap-calculator: ^1.7.1
  - @loopback/service-proxy: ^1.3.12
  - @loopback/http-caching-proxy: ^1.2.2
  - @loopback/http-server: ^1.4.19
  - @loopback/example-todo-list: ^1.12.1
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.4.5
  - @loopback/eslint-config: ^4.1.5
  - @loopback/example-express-composition: ^1.9.1
  - @loopback/example-greeter-extension: ^1.3.20
  - @loopback/booter-lb3app: ^1.3.6
  - @loopback/example-lb3-application: ^1.1.20
  - @loopback/example-greeting-app: ^1.2.6
  - @loopback/example-context: ^1.2.20
  - @loopback/repository-tests: ^0.7.0
  - @loopback/extension-health: ^0.2.12
  - @loopback/authorization: ^0.4.5
  - @loopback/rest-crud: ^0.6.1
  - @loopback/security: ^0.1.8
  - @loopback/authentication-passport: ^1.0.5
  - @loopback/example-metrics-prometheus: ^0.1.1
  - @loopback/extension-metrics: ^0.1.1
```

**Comment by bajtos** [comment]
@johnhaire89 can you reproduce the problem using `loopback-connector-postgresql` version `4.0.0`? If yes, then please: 
- Create a small LB4 application we can use to reproduce the issue in isolation - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report.
- Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.
- Open a new issue either in this repository or in loopback-next.

**Comment by bajtos** [comment]
@johnhaire89 sorry for the confusion, I see that the latest version of `loopback-connector-postgresql` is `3.8.0`  and that's the version you tried & reproduced the problem with.

To help us to help you, please create a small application we can use to reproduce the problem and open a new issue. 

- Create a small LB4 application we can use to reproduce the issue in isolation - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report.
- Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.
- Open a new issue either in this repository or in loopback-next.
